### ISSUE TITLE
Product details screen >> prices are varying

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#1]
Product details screen >> prices are varying

i.e. Banana chips showing rs 200 but when added to cart it reduces to 11

![screenshot_2018-01-07-18-09-43-944_com lapalap](https://user-images.githubusercontent.com/19631677/34649490-5fea1312-f3d6-11e7-98ad-901a95708914.png)
![screenshot_2018-01-07-18-09-34-968_com lapalap](https://user-images.githubusercontent.com/19631677/34649491-6024cdf4-f3d6-11e7-9b1f-f4162a3e14db.png)

**Comment by scubesvn** [comment]
Fixed!
