### ISSUE TITLE
When user adds something in wishlist by tapping on heart icon it should get filled completely.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#10]
When user adds something in wishlist by tapping on heart icon it should get filled completely.

![screenshot_2018-01-07-19-21-33-386_com lapalap 1](https://user-images.githubusercontent.com/19631677/34650031-fe737eac-f3df-11e7-8962-447f37837d6a.png)

**Comment by scubesvn** [comment]
Fixed.
