### ISSUE TITLE
Invite code must not be 'null' it should be alphanumeric character.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#12]
Invite code must not be 'null' it should be alphanumeric character.

![screenshot_2018-01-07-19-23-21-292_com lapalap 1](https://user-images.githubusercontent.com/19631677/34650089-d6e52b32-f3e0-11e7-8bf9-528008b4fc3d.png)

**Comment by scubesvn** [comment]
This user created by either WEB or Mobile? Kindly confirm.

**Comment by Munish7986** [comment]
@scubesvn This user is created from web.

**Comment by scubesvn** [comment]
@Munish7986 we have fixed it for new user registration. You will need to create new user and will get invite code.
