### ISSUE TITLE
Time for reporting complaint is not correct. i.e. when user files a compliant at 7:00 pm it says 7:00 am on customer end.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#14]
Time for reporting complaint is not correct. i.e. when user files a compliant at 7:00 pm it says 7:00 am on customer end.

![screenshot_2018-01-07-19-36-52-784_com lapalap 1](https://user-images.githubusercontent.com/19631677/34650170-688c41be-f3e2-11e7-9ced-89236fcb43e8.png)

**Comment by scubesvn** [comment]
Fixed!
