### ISSUE TITLE
Showing different order id's on different screens.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#15]
Showing different order id's on different screens.

![screenshot_2018-01-07-19-36-52-784_com lapalap 1](https://user-images.githubusercontent.com/19631677/34650183-96ad354e-f3e2-11e7-9249-6a6fdfaa2689.png)
![screenshot_2018-01-07-19-39-20-216_com lapalap 1](https://user-images.githubusercontent.com/19631677/34650186-9b588634-f3e2-11e7-81ab-4a1184ee4083.png)

**Comment by scubesvn** [comment]
Fixed!
