### ISSUE TITLE
Time on Notifications screen is wrong. i.e that displays 7:00 am instead of 7:00 pm

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#17]
Time on Notifications screen is wrong. i.e that displays 7:00 am instead of 7:00 pm

![screenshot_2018-01-07-19-42-21-209_com lapalap 1](https://user-images.githubusercontent.com/19631677/34650212-169aa322-f3e3-11e7-8f57-1f1a6e6ee86d.png)

**Comment by scubesvn** [comment]
Fixed!
