### ISSUE TITLE
On sign up>> if using already used ph number>> shows incorrect validation

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#19]
On sign up>> if using already used ph number>> shows incorrect validation
i.e. saying Invalid phone number. but it should be Already resgitered

**Comment by scubesvn** [comment]
I am getting correct message "You are already a registered user". For reference, kindly look at screenshot.
![screenshot_20180108-120035](https://user-images.githubusercontent.com/28253360/34661471-f8305d90-f46f-11e7-83a0-cda1b9ce285a.jpg)
