### ISSUE TITLE
When add product to the cart>> itshows 0 count on cart icon on home screen 

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#2]
When add product to the cart>> itshows 0 count on cart icon on home screen 

![screenshot_2018-01-07-18-13-50-060_com lapalap 1](https://user-images.githubusercontent.com/19631677/34649537-2f9f0c98-f3d7-11e7-9133-ca37e584e9f5.png)
![screenshot_2018-01-07-18-09-34-968_com lapalap 1](https://user-images.githubusercontent.com/19631677/34649540-39ec09e4-f3d7-11e7-994b-fcd5a74342e5.png)

**Comment by scubesvn** [comment]
Fixed!
