### ISSUE TITLE
Email not fetched when user login via google

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#24]
When user login with google, previously added addresses(address of last logged in customer) are displayed  >> When user logs in by selecting any address then in profile no name, email is displayed

![screenshot_2018-01-13-12-08-31-516_com lapalap 1](https://user-images.githubusercontent.com/19631677/34903593-88f28c7a-f85a-11e7-96b2-6f53929b2b53.png)

![screenshot_2018-01-13-11-38-31-766_com lapalap 1](https://user-images.githubusercontent.com/19631677/34903590-85e93b0a-f85a-11e7-9a3c-e23ef7285546.png)

**Comment by scubesvn** [comment]
@Munish7986 Now if user will login using Google+/Facebook, we are fetching the email address and you should be able to see it in myprofile section. Kindly test.
