### ISSUE TITLE
Blank screen appears when user taps on search icon followed by cross icon.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#27]
Blank screen appears when user taps on search icon followed by cross icon.

![screenshot_2018-01-13-16-13-46-085_com lapalap 1](https://user-images.githubusercontent.com/19631677/34905367-1683b04c-f87d-11e7-80cd-616e37f2d561.png)

**Comment by scubesvn** [comment]
I have removed close button for first time click on search icon.
1) Click on Search icon from slide menu.
2) it will ask for type the search keyword.
3) I hide close button. so user can not close the search bar.
4) Screen will be black until user type some thing.
