### ISSUE TITLE
User is unable to delete an item from wishlist by tapping on heart icon twice.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#3]
User is unable to delete an item from wishlist by tapping on heart icon twice.

Expected result : item should get deleted from the wishlist when user taps on heart icon two times

![screenshot_2018-01-07-18-37-48-119_com lapalap 1](https://user-images.githubusercontent.com/19631677/34649681-e476bf4c-f3d9-11e7-81e6-06485053b872.png)
![screenshot_2018-01-07-18-37-39-510_com lapalap 1](https://user-images.githubusercontent.com/19631677/34649684-ed61ce4e-f3d9-11e7-82af-c7d0445837a4.png)

**Comment by scubesvn** [comment]
Fixed!

**Comment by scubesvn** [comment]
Kindly write your testing steps. These are my steps:
1) Go to product list.
2) Add the item in wish list. 
3) Go to Wish List and remove all items.
4) Again go to product list and double tap on heart icon, it will remove or add the items.

**Comment by scubesvn** [comment]
It has been fixed before 22 days and sill not closed. Kindly test.
