### ISSUE TITLE
My profile >> Change password (Suggestion)

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#4]
My profile >> Change password (Suggestion)
1. New password should be different from old password. Right now it is accepting the old password as new password.
2. There is no max and min limit for password fields. It should be 6 - 12 characters. 
3. Validation messages are not user friendly. 
    If user is entering wrong old password validation message should be 'Incorrect old password'
    If new password and confirm  new passwords do not match validation message should be 'Password do not match'

**Comment by scubesvn** [comment]
We have fixed point number 1,2,3. But we can not say to user that old password is incorrect.They have to enter correct old password if they remember they can otherwise we just sending them a hint about old password incorrect. Thanks!
