### ISSUE TITLE
If user adds a product from product description screen >> count of the the cart is not increased.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#41]
If user adds a product from product description screen >> count of the the cart is not increased.

![screenshot_2018-01-27-13-05-12-615_com lapalap 1](https://user-images.githubusercontent.com/19631677/35469795-f3fd0c1c-0362-11e8-82b9-cb83ed25e2e8.png)

![screenshot_2018-01-27-13-05-18-283_com lapalap 1](https://user-images.githubusercontent.com/19631677/35469788-db3998bc-0362-11e8-812a-039ae98b1965.png)

![screenshot_2018-01-27-13-05-25-257_com lapalap 1](https://user-images.githubusercontent.com/19631677/35469785-d0ed114a-0362-11e8-9919-5c54b51ae72f.png)

**Comment by scubesvn** [comment]
Fixed!
