### ISSUE TITLE
When user login with Facebook or Google+ and then goes to my profile, it keeps showing Email address field blank.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#42]
When user login with Facebook or Google+ and then goes to my profile, it keeps showing Email address field blank.
![screenshot_2018-01-27-14-42-07-561_com lapalap 1](https://user-images.githubusercontent.com/19631677/35470612-8656b72a-0372-11e8-8bfa-f2726a41f05f.png)

**Comment by scubesvn** [comment]
@Munish7986 Please try now.
