### ISSUE TITLE
When an order is placed successfully, message should be displayed as 'Order placed successfully' instead of 'Order completed successfully'.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#44]
When an order is placed successfully, message should be displayed as 'Order placed successfully' instead of 'Order completed successfully'.

![screenshot_2018-01-28-11-21-00-900_com lapalap 1](https://user-images.githubusercontent.com/19631677/35479439-9054a218-041d-11e8-9047-149770ee0a54.png)

**Comment by scubesvn** [comment]
Fixed!
