### ISSUE TITLE
Price of Gift wrap is not added in the total amount after the order has been placed

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#45]
Price of Gift wrap is not added in the total amount after the order has been placed

![screenshot_2018-01-28-12-01-21-479_com lapalap 1](https://user-images.githubusercontent.com/19631677/35479744-68852a4e-0424-11e8-8417-e11a48c62cee.png)

**Comment by scubesvn** [comment]
Fixed!
