### ISSUE TITLE
When user selects state dropdown, Uttar Pradesh is appearing twice.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#5]
Add address screen
1. when user selects state dropdown, Uttar Pradesh is appearing twice.
2. UI of the pincode field gets distorted while entering data into the fields.
3. There is no limit for pincode field. It should be 6-12 digits

![screenshot_2018-01-07-18-52-28-271_com lapalap 1](https://user-images.githubusercontent.com/19631677/34649811-2ff1593a-f3dc-11e7-8143-a08f1941ed77.png)
![screenshot_2018-01-07-18-55-00-935_com lapalap 1](https://user-images.githubusercontent.com/19631677/34649835-b1fcb154-f3dc-11e7-82a0-02145d3217bc.png)

**Comment by scubesvn** [comment]
Fixed!
