### ISSUE TITLE
When user taps in notes field watermark should disappear, Right now it is not disappearing.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#6]
Add address page 
When user taps in notes field watermark should disappear, Right now it is not disappearing.

![screenshot_2018-01-07-19-04-11-773_com lapalap 1](https://user-images.githubusercontent.com/19631677/34649900-92494a92-f3dd-11e7-8f4b-defd4e4fd76e.png)

**Comment by scubesvn** [comment]
This is Android component behaviour. It will remove the hint when user will press any key or type data.
