### ISSUE TITLE
Wish list  >> Crash is happening when user taps on back button followed by tap on grid view button 

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#8]
Wish list  >> Crash is happening when user taps on back button followed by tap on grid view button 

![screenshot_2018-01-07-19-14-31-460_com lapalap 1](https://user-images.githubusercontent.com/19631677/34649986-33c4cee0-f3df-11e7-8d33-f87bac33fd1b.png)

**Comment by scubesvn** [comment]
Fixed!
