### ISSUE TITLE
Placement of list/grid view icon is different for the screens having records and where there is no record.

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#9]
Placement of list/grid view icon is different for the screens having records and where there is no record.

![screenshot_2018-01-07-19-16-06-470_com lapalap 1](https://user-images.githubusercontent.com/19631677/34650006-7ce36cb2-f3df-11e7-8477-3e27b18e8677.png)
![screenshot_2018-01-07-19-16-10-346_com lapalap 1](https://user-images.githubusercontent.com/19631677/34650009-82d212c2-f3df-11e7-87c9-ddafb2f8d58e.png)

**Comment by scubesvn** [comment]
Fixed!
